AceJobAgency/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace AceJobAgency.Models
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; } = string.Empty;
        public bool RememberMe { get; set; }

    }
}

AceJobAgency/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AceJobAgency.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }
        public int StatusCode { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet(int statusCode)
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            StatusCode = statusCode;
        }
    }
}

AceJobAgency/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    [Authorize]

    public class IndexModel : PageModel

    {

        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

AceJobAgency/Pages/Login.cshtml.cs
using AceJobAgency.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    public class LoginModel : PageModel
    {

        [BindProperty]
        public Login LModel { get; set; }

        private readonly SignInManager<Membership> signInManager;
        public LoginModel(SignInManager<Membership> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }
        protected void LogoutMe(object sender, EventArgs e)
        {

        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password,LModel.RememberMe, lockoutOnFailure:true);
                if (identityResult.IsLockedOut)
                {
                    
                    ModelState.AddModelError("", "Account locked out due to too many failed login attempts. Please try again later.");
                    return Page();

                }
                else
                {
                    if (identityResult.Succeeded)
                    {
                        var user = await signInManager.UserManager.GetUserAsync(User);
                        HttpContext.Session.SetString("UserId", user.Id);
                        return RedirectToPage("Index");
                    }
                    ModelState.AddModelError("", "Username or Password incorrect");

                }
                        }
            return Page();
        }


    }
}

AceJobAgency/Pages/Logout.cshtml.cs
using AceJobAgency.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    public class LogoutModel : PageModel
    {

        private readonly SignInManager<Membership> signInManager;
        public LogoutModel(SignInManager<Membership> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet() { }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            HttpContext.Session.Clear();


            return RedirectToPage("Login");
        }
        public async Task<IActionResult> OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

AceJobAgency/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    [Authorize]

    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AceJobAgency/Pages/Profile.cshtml.cs
using AceJobAgency.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.DataProtection;


namespace AceJobAgency.Pages
{
    public class ProfileModel : PageModel
    {
        private UserManager<Membership> userManager { get; }
        private SignInManager<Membership> signInManager { get; }

        public Membership MModel { get; set; } = new();


        public ProfileModel(UserManager<Membership> userManager, SignInManager<Membership> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public async Task<IActionResult> OnGet()
        {
            var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
            var protector = dataProtectionProvider.CreateProtector("MySecretKey");
            if (HttpContext.Session.GetString("UserId")  == null)
            {
                return RedirectToPage("/Login");

            }
            var user = await userManager.GetUserAsync(User);

            if (user == null)
            {
                return Redirect("/Login");
            }
            else
            {
                MModel.FirstName = user.FirstName;
                MModel.LastName = user.LastName;
                MModel.NRIC = protector.Unprotect(user.NRIC);
                MModel.WhoamI = user.WhoamI;





                return Page();
            }




        }

    }
}

AceJobAgency/Pages/Registeration.cshtml.cs
using AceJobAgency.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Win32;
using System.Diagnostics;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.NetworkInformation;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Text;
using Newtonsoft.Json;
using Microsoft.AspNetCore.DataProtection;




namespace AceJobAgency.Pages
{
    public class RegisterationModel : PageModel
    {
        private IWebHostEnvironment _environment;

        public IFormFile? Upload { get; set; }
        private UserManager<Membership> userManager { get; }
        private SignInManager<Membership> signInManager { get; }
        private readonly RoleManager<IdentityRole> roleManager;

        [BindProperty]
        public Membership MModel { get; set; } = new();
        public RegisterationModel(UserManager<Membership> userManager,
        SignInManager<Membership> signInManager, IWebHostEnvironment environment, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            _environment = environment;
            this.roleManager = roleManager;
        }

        public async Task<IActionResult> OnPostAsync()
        {

            if (ModelState.IsValid)
            {
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("MySecretKey");
                /*                var response = HttpContext.Request.Form["g-recaptcha-response"];
                                var captchaValid = await VerifyCaptchaResponse(response);*/
                /*
                                if (!captchaValid)
                                {
                                    ModelState.AddModelError("", "Captcha validation failed. Please try again.");
                                    return Page();
                                }
                */
                if (Upload != null)
                {
                    if (!(Upload.FileName.EndsWith(".docx") || Upload.FileName.EndsWith(".pdf")))
                    {
                        ModelState.AddModelError("Upload","Invalid file format. Only .docx and .pdf formats are allowed");
                        return Page();
                    }
                    if (Upload.Length > 2 * 1024 * 1024)
                    {
                        ModelState.AddModelError("Upload", "File size cannot exceed 2MB.");
                        return Page();
                    }
                    var uploadsFolder = "uploads";
                    var imageFile = Guid.NewGuid() + Path.GetExtension(
                    Upload.FileName);
                    var imagePath = Path.Combine(_environment.ContentRootPath, "wwwroot", uploadsFolder, imageFile);
                    Debug.WriteLine(imagePath);
                    using var fileStream = new FileStream(imagePath, FileMode.Create);
                    await Upload.CopyToAsync(fileStream);
                    MModel.ResumeURL = string.Format("/{0}/{1}", uploadsFolder, imageFile);
                }


                var user = new Membership()
                {
                    FirstName = MModel.FirstName,
                    LastName = MModel.LastName,
                    Gender = MModel.Gender,
                    NRIC = protector.Protect(MModel.NRIC),
                    Email = MModel.Email,
                    DateOfBirth = MModel.DateOfBirth,
                    ResumeURL = MModel.ResumeURL,
                    WhoamI = MModel.WhoamI,
                    UserName = MModel.Email
                };
                //Create the Admin role if NOT exist
                IdentityRole role = await roleManager.FindByIdAsync("Admin");
                if (role == null)
                {
                    IdentityResult result2 = await roleManager.CreateAsync(new IdentityRole("Admin"));
                    if (!result2.Succeeded)
                    {
                        ModelState.AddModelError("", "Create role admin failed");
                    }
                }



                var result = await userManager.CreateAsync(user, MModel.Password);
                if (result.Succeeded)
                {
                    result = await userManager.AddToRoleAsync(user, "Admin");
                    await signInManager.SignInAsync(user, false);
                    HttpContext.Session.SetString("UserId", user.Id);
                    return RedirectToPage("Login");
                }

                foreach (var error in result.Errors)
                {

                    ModelState.AddModelError("", error.Description);

                }


            }
            return Page();
        }

/*        private async Task<bool> VerifyCaptchaResponse(string response)
        {
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/x-www-form-urlencoded"));

                var secretKey = "6Lf-zVUkAAAAAMjxZ__UzmMS7Gbbw2d9y-26cM14";
                var request = $"secret={secretKey}&response={response}";
                var content = new StringContent(request, Encoding.UTF8, "application/x-www-form-urlencoded");

                var responseMessage = await client.PostAsync("https://www.google.com/recaptcha/api/siteverify", content);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var result = await responseMessage.Content.ReadAsStringAsync();
                    var resultObject = JsonConvert.DeserializeObject<dynamic>(result);
                    if (resultObject.success)
                    {
                        return true;
                    }
                }
            }

            return false;
        }*/





        public void OnGet()
        {
        }
    }
}

AceJobAgency/Pages/Index.cshtml
@page
@inject IHttpContextAccessor contxt;
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>


</div>

AceJobAgency/Pages/Login.cshtml
@page
@model AceJobAgency.Pages.LoginModel
@{
}

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>

			<form method="post">
				@if (!ModelState.IsValid)
				{
					<div class="alert alert-danger">
						@foreach (var error in ModelState.Values.SelectMany(m => m.Errors))
						{
							<p>@error.ErrorMessage</p>
						}
					</div>
				}
				
				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input  asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Login</button>
				</div>
			</form>
		</div>
	</div>
</div>

AceJobAgency/Pages/Logout.cshtml
@page
@model AceJobAgency.Pages.LogoutModel
@{
}

<form method="post">
	<div class="container mt-5">
		<div class="row justify-content-center">
			<div class="col-sm-12 col-md-12 col-lg-4">
				<p> Are you sure you want to logout? </p>
				<p> 
					<button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
					<button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
				</p>
			</div>
		</div>	
	</div>
</form>

AceJobAgency/Pages/Profile.cshtml
@page
@model AceJobAgency.Pages.ProfileModel
@{
    ViewData["Title"] = "Profile";

}
<h1 class="display-4">@ViewData["Title"]</h1>

<div>
    <div>
        <label class="col-sm-2 col-form-label">
            @Html.DisplayNameFor(
            m => m.MModel.FirstName):
        </label>
        <label>@Model.MModel.FirstName</label>
    </div>
    <div>
        <label class="col-sm-2 col-form-label">
            @Html.DisplayNameFor(
            m => m.MModel.LastName):
        </label>
        <label>@Model.MModel.LastName</label>
    </div>
    <div>
        <label class="col-sm-2 col-form-label">
            @Html.DisplayNameFor(
            m => m.MModel.Gender):
        </label>
        <label>@Model.MModel.Gender</label>
    </div>
    <div>
        <label class="col-sm-2 col-form-label">
            @Html.DisplayNameFor(
            m => m.MModel.NRIC):
        </label>
        <label>@Model.MModel.NRIC</label>
    </div>
    <div>
        <label class="col-sm-2 col-form-label">
            @Html.DisplayNameFor(
            m => m.MModel.DateOfBirth):
        </label>
        <label>@Model.MModel.DateOfBirth.ToShortDateString()</label>
    </div>
    <div>
        <label class="col-sm-2 col-form-label">
            @Html.DisplayNameFor(
            m => m.MModel.WhoamI):
        </label>
        <label>@Model.MModel.WhoamI</label>
    </div>
  
    <div class="mt-3">
        <a class="btn btn-secondary" id="backbtn" href="/Index">Back</a>
    </div>
</div>

AceJobAgency/Pages/Registeration.cshtml
@page
@model AceJobAgency.Pages.RegisterationModel
@{
    ViewData["Title"] = "Register Member";

}

<h1 class="display-4">@ViewData["Title"]</h1>

<form class="mt-3" method="post" asp-antiforgery="true" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row mb-3">
        @if (!ModelState.IsValid)
        {
            <div class="alert alert-danger">
                @foreach (var error in ModelState.Values.SelectMany(m => m.Errors))
                {
                    <p>@error.ErrorMessage</p>
                }
            </div>
        }
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label" asp-for="MModel.FirstName"></label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="MModel.FirstName" />
                <span asp-validation-for="MModel.FirstName" class="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label" asp-for="MModel.LastName"></label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="MModel.LastName" />
                <span asp-validation-for="MModel.LastName" class="text-danger"></span>
            </div>
        </div>

        <div class="row mb-3">
            <label class="col-sm-2 col-form-label"  asp-for="MModel.Gender"></label>
            <div class="col-sm-10">

            <select asp-for="MModel.Gender" asp-items="Html.GetEnumSelectList<AceJobAgency.Models.Gender>()" class="form-control"></select>
            <span asp-validation-for="MModel.Gender" class="text-danger"></span>
            </div>
        </div>

        <div class="row mb-3">
            <label class="col-sm-2 col-form-label" asp-for="MModel.NRIC"></label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="MModel.NRIC" />
                <span asp-validation-for="MModel.NRIC" class="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label" asp-for="MModel.Email"></label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="MModel.Email" />
                <span asp-validation-for="MModel.Email" class="text-danger"></span>
            </div>
        </div>

        <div class="row mb-3">
            <label class="col-sm-2 col-form-label" asp-for="MModel.Password"></label>
            <div class="col-sm-10">
                <input class="form-control" id="password" onkeyup="checkPasswordStrength()" asp-for=" MModel.Password" />
                <span asp-validation-for="MModel.Password" class="text-danger"></span>
                <div id="password-feedback"></div>
            </div>
        </div>

        <div class="row mb-3">
            <label class="col-sm-2 col-form-label" asp-for="MModel.ConfirmPassword"></label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="MModel.ConfirmPassword" />
                <span asp-validation-for="MModel.ConfirmPassword" class="text-danger"></span>
            </div>
        </div>

        <div class="row mb-3">
            <label class="col-sm-2 col-form-label" asp-for="MModel.DateOfBirth"></label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="MModel.DateOfBirth" />
                <span asp-validation-for="MModel.DateOfBirth" class="text-danger"></span>
            </div>
        </div>


        <div class="row mb-3">
            <label class="col-sm-2 col-form-label" asp-for="MModel.WhoamI"></label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="MModel.WhoamI" />
                <span asp-validation-for="MModel.WhoamI" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-3">
            <label class="col-sm-2 col-form-label" asp-for="MModel.ResumeURL"></label>

            <div class="col-sm-10">
                <input type="file" accept="image/*" asp-for="MModel.ResumeURL"
                       class="form-control" />
                <span asp-validation-for="MModel.ResumeURL" class="text-danger"></span>
            </div>
        </div>
        <div class="mt-3">

@*            <div class="g-recaptcha" data-sitekey="6Lf-zVUkAAAAAMtDpY7eZVUddjCPEHkIBkR-zO7o"></div>
*@
        <input type="submit" value="Register" class="btn btn-primary" />
        </div>




       




    </div>
@*    <script src='https://www.google.com/recaptcha/api.js?render=6Lf-zVUkAAAAAMtDpY7eZVUddjCPEHkIBkR-zO7o'></script>
*@


</form>
<script>
  function checkPasswordStrength() {
    // Get the password input
    var password = document.getElementById("password").value;

    // Initialize a variable to store the password strength
    var strength = 0;

    // Check if the password is at least 8 characters long
    if (password.length >= 12) {
      strength += 1;
    }

    // Check if the password contains at least one lowercase letter
    if (/[a-z]/.test(password)) {
      strength += 1;
    }

    // Check if the password contains at least one uppercase letter
    if (/[A-Z]/.test(password)) {
      strength += 1;
    }

    // Check if the password contains at least one number
    if (/\d/.test(password)) {
      strength += 1;
    }

    // Check if the password contains at least one special character
    if (/[!#$%^&*]/.test(password)) {
      strength += 1;
    }

    // Display the password strength
    var passwordFeedback = document.getElementById("password-feedback");
    passwordFeedback.innerHTML = "Password Strength: " + strength + "/5";

    // Change the color of the password strength based on its value
    switch (strength) {
      case 0:
        passwordFeedback.style.color = "red";
        break;
      case 1:
        passwordFeedback.style.color = "darkred";
        break;
      case 2:
        passwordFeedback.style.color = "orange";
        break;
      case 3:
        passwordFeedback.style.color = "lightgreen";
        break;
      case 4:
        passwordFeedback.style.color = "green";
        break;
      case 5:
        passwordFeedback.style.color = "darkgreen";
        break;
    }
  }
</script>